# ============================================================
# PHASE 3 — Binance Adapter (Crypto)
# ============================================================
# Install when ready: pip install python-binance
#
# class BinanceBroker:
#     """
#     Drop-in replacement for AlpacaBroker when trading crypto.
#     Implements the same interface as AlpacaBroker.
#     """
#     def __init__(self): ...
#     def get_account(self): ...
#     def get_positions(self): ...
#     async def place_order(self, symbol, side, qty, strategy_name): ...
#     async def get_latest_price(self, symbol): ...
#     def get_bars(self, symbol, timeframe, limit): ...
#
#     # Crypto-specific extras:
#     def get_order_book(self, symbol): ...
#     def get_funding_rate(self, symbol): ...
# ============================================================
