# ============================================================
# PHASE 2 — Interactive Brokers Adapter (Options)
# ============================================================
# Install when ready: pip install ibapi
#
# class IBKRBroker:
#     """
#     Drop-in replacement for AlpacaBroker when trading options.
#     Implements the same interface: get_account(), get_positions(),
#     place_order(), get_latest_price(), get_bars()
#     """
#     def __init__(self): ...
#     def get_account(self): ...
#     def get_positions(self): ...
#     async def place_order(self, symbol, side, qty, strategy_name): ...
#     async def get_latest_price(self, symbol): ...
#     def get_bars(self, symbol, timeframe, limit): ...
#
#     # Options-specific extras:
#     def get_option_chain(self, symbol, expiry): ...
#     def get_greeks(self, contract): ...
# ============================================================
